// ==UserScript==
// @name         IRC-to-Gitter bridge bot integration
// @description  Substitute nicknames in messages written by @FromIRC (bridge bot)
// @version      6
// @include      https://gitter.im/*
// @include      https://app.element.io/*
// @grant        none
// @require      https://code.jquery.com/jquery-3.5.1.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.18.0/js/md5.min.js
// @run-at       document-start
// @author       Oleh Prypin
// @namespace    http://pryp.in/
// ==/UserScript==
// Generated by LiveScript 1.6.0
var $, one, matrix, sel, update, mutationObserver, currentChatContainer, register;
$ = jQuery;
one = function(it){
  if (it.length) {
    return it;
  }
};
matrix = window.location.href.startsWith('https://app.element.io/');
sel = function(g, m){
  if (matrix) {
    return m;
  } else {
    return g;
  }
};
update = function(){
  var replacing, prevNickname, someAvatar, someProfile;
  replacing = false;
  prevNickname = null;
  someAvatar = someProfile = null;
  $(sel('#chat-container .chat-item', '.mx_RoomView_MessageList>li.mx_EventTile')).each(function(){
    var that, avatar, profile, x$, nickname;
    if (that = one($(this).find(sel('.chat-item__username', '.mx_SenderProfile_displayName')))) {
      replacing = that.text() === sel('@FromIRC', 'FromIRC (From IRC (bridge bot))') || that.hasClass('irc-from');
    }
    if (avatar = one($(this).find(sel('.chat-item__aside', '.mx_EventTile_avatar')))) {
      someAvatar = avatar;
    }
    if (profile = one($(this).find(sel('.chat-item__details', '.mx_SenderProfile')))) {
      someProfile = profile;
    }
    if (replacing) {
      x$ = $(this).find(sel('.chat-item__text strong', '.mx_EventTile_content strong')).first();
      nickname = x$.text();
      x$.hide();
      if (nickname.includes('* ')) {
        $(this).addClass('chat-item__status');
        nickname = nickname.replace('* ', '');
      }
      if (avatar || nickname !== prevNickname) {
        $(this).removeClass(sel('burstContinued', 'mx_EventTile_continuation')).addClass(sel('burstStart', null));
        if (!avatar) {
          avatar = someAvatar.clone();
          sel(function(it){
            return it.prepend(avatar);
          }, function(it){
            return it.append(avatar);
          })(
          sel(function(it){
            return it.find(sel('.chat-item__container'));
          }, function(it){
            return it;
          })(
          $(this)));
        }
        avatar.find('img').attr({
          src: "https://secure.gravatar.com/avatar/" + md5(nickname) + "?s=30&d=identicon",
          srcset: null
        });
        if (!profile) {
          profile = someProfile.clone();
          (function(it){
            return it.prepend(profile);
          })(
          sel(function(it){
            return it.find('.chat-item__content');
          }, function(it){
            return it;
          })(
          $(this)));
        }
        $(this).find(sel('.chat-item__from', '.mx_SenderProfile_displayName')).text(nickname).removeClass('js-chat-item-from').addClass('irc-from');
        profile.find('.chat-item__username').hide();
      }
    }
    prevNickname = nickname;
  });
  mutationObserver.takeRecords();
};
mutationObserver = new MutationObserver(update);
currentChatContainer = null;
register = function(){
  var chatContainer;
  chatContainer = $(sel('#chat-container', '.mx_RoomView_MessageList'));
  if (!chatContainer.length || chatContainer[0] === currentChatContainer) {
    return;
  }
  currentChatContainer = chatContainer[0];
  update();
  mutationObserver.observe(chatContainer[0], {
    childList: true,
    subtree: true
  });
  chatContainer.on('click', '.irc-from', function(){
    var nickname, textarea, div;
    nickname = $(this).text().replace(/^<|>$/g, '');
    if (matrix) {
      textarea = $('.mx_BasicMessageComposer_input');
      div = textarea.children(':first');
      div.html(nickname + ", " + div.html());
    } else {
      textarea = $('.chat-input__text-area');
      textarea.val(nickname + ", " + textarea.val());
    }
    return false;
  });
};
setInterval(register, 500);
