// ==UserScript==
// @name         IRC-to-Gitter bridge bot integration
// @description  Substitute nicknames in messages written by @FromIRC (bridge bot)
// @version      2
// @include      https://gitter.im/*
// @grant        none
// @require      https://code.jquery.com/jquery-3.3.1.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.10.0/js/md5.min.js
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://pryp.in/
// ==/UserScript==
// Generated by LiveScript 1.5.0
var $, one, update, mutationObserver;
$ = jQuery;
one = function(it){
  if (it.length) {
    return it;
  }
};
update = function(){
  var replacing, prevNickname, someAside, someDetails;
  replacing = false;
  prevNickname = null;
  someAside = someDetails = null;
  $('.chat-item').each(function(){
    var that, x$, nickname, aside, details;
    if (that = one($(this).find('.chat-item__username'))) {
      replacing = that.text() === '@FromIRC';
    }
    if (replacing) {
      x$ = $(this).find('.chat-item__text strong');
      nickname = x$.text();
      x$.hide();
      if (nickname.includes('* ')) {
        $(this).addClass('chat-item__status');
        nickname = nickname.replace('* ', '');
      }
      aside = one($(this).find('.chat-item__aside'));
      if (aside || nickname !== prevNickname) {
        $(this).removeClass('burstContinued').addClass('burstStart');
        if (aside) {
          someAside = aside;
        } else {
          aside = someAside.clone();
          $(this).find('.chat-item__container').prepend(aside);
        }
        aside.find('img').attr({
          src: "https://secure.gravatar.com/avatar/" + md5(nickname) + "?s=30&d=identicon"
        });
        if (details = one($(this).find('.chat-item__details'))) {
          someDetails = details;
        } else {
          details = someDetails.clone();
          $(this).find('.chat-item__content').prepend(details);
        }
        $(this).find('.chat-item__from').text(nickname).removeClass('js-chat-item-from').addClass('irc-from');
        details.find('.chat-item__username').hide();
      }
    }
    prevNickname = nickname;
  });
  mutationObserver.takeRecords();
};
mutationObserver = new MutationObserver(update);
mutationObserver.observe($('#chat-container')[0], {
  childList: true,
  subtree: true
});
$('#chat-container').on('click', '.irc-from', function(){
  var nickname, textarea;
  nickname = $(this).text().replace(/^<|>$/g, '');
  textarea = $('.chat-input__text-area');
  return textarea.val(nickname + ", " + textarea.val());
});
