// ==UserScript==
// @name         SteamDB sales page improvements
// @description  Add controls to hide non-"highest recorded discount"
// @version      11
// @include      https://steamdb.info/sales/*
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://blaxpirit.com/
// ==/UserScript==
// Generated by LiveScript 1.6.0
var $, x$, i$, ref$, len$, cls, filters, res$, kind;
$ = jQuery;
applyStyle('#visibility-filter { text-align: center; margin-right: 20px; float: left; }#visibility-filter table { background-color: transparent; margin: 0 auto; }#visibility-filter tr :first-child { text-align: right; }#visibility-filter input { width: 70px; }.visibility-filter-hidden { display: none; }.header-sales-filters, .header-sales-info, .header-sales-filters>* { width: auto !important; height: auto !important; }.header-sales-info * { z-index: 1; }.tag-exclusion-hint { display: none; }');
$('.dataTables_length select').val(-1).change();
x$ = $('#js-wishlisted-only, #js-hide-owned-games, #js-highest-new-only');
x$.filter('.checked').click();
x$.hide();
for (i$ = 0, len$ = (ref$ = ['daily-deal', 'special-promotion', 'play-for-free', 'todays-highlighted-deals']).length; i$ < len$; ++i$) {
  cls = ref$[i$];
  $('td.sales-' + cls).removeClass('sales-' + cls);
}
for (i$ = 0, len$ = (ref$ = ['weeklong-deals', 'more-highlighted-deals']).length; i$ < len$; ++i$) {
  cls = ref$[i$];
  $('.sales-' + cls).removeClass('sales-' + cls);
}
$('<div id="visibility-filter" class="fancy-price"><table><tr><th>Display games:</th><td>Wishlist</td><th>Default</th><td>Owned</td></tr><tr><td>Any discount</td><td><input type="radio" name="filter-wish" value="all"></td><td><input type="radio" name="filter-all" value="all"></td><td><input type="radio" name="filter-own" value="all"></td></tr><tr><td>Hide smaller discounts</td><td><input type="radio" name="filter-wish" value="le" checked></td><td><input type="radio" name="filter-all" value="le"></td><td><input type="radio" name="filter-own" value="le"></td></tr><tr><td>Only new highest discounts</td><td><input type="radio" name="filter-wish" value="lt"></td><td><input type="radio" name="filter-all" value="lt" checked></td><td><input type="radio" name="filter-own" value="lt"></td></tr><tr><td>Hide</td><td><input type="radio" name="filter-wish" value="none"></td><td><input type="radio" name="filter-all" value="none"></td><td><input type="radio" name="filter-own" value="none" checked></td></tr></table></div>').prependTo('#js-filters');
$('#js-filter-submit').appendTo('.span-sale-filter:first').text('Reload');
function check(row, cond){
  switch (cond) {
  case 'all':
    return true;
  case 'le':
    return row.find('.highest-discount').length === 0;
  case 'lt':
    return row.find('.highest-discount-major').length > 0;
  case 'none':
    return false;
  }
}
res$ = {};
for (i$ = 0, len$ = (ref$ = ['wish', 'all', 'own']).length; i$ < len$; ++i$) {
  kind = ref$[i$];
  res$[kind] = $('#visibility-filter input[name="filter-' + kind + '"]');
}
filters = res$;
function byIndex(kind, index){
  if (index != null) {
    filters[kind].get(index).click();
  }
  return filters[kind].index(filters[kind].filter(':checked'));
}
function byVal(kind, val){
  if (val != null) {
    filters[kind].filter('[value="' + val + '"]').click();
  }
  return filters[kind].filter(':checked').val();
}
for (kind in filters) {
  try {
    byVal(kind, GM_getValue(kind));
  } catch (e$) {}
}
function updateFilters(){
  var kind;
  if (byIndex('wish') > byIndex('all')) {
    byIndex('wish', byIndex('all'));
    return;
  }
  $('.table-sales tr.app').each(function(){
    var row, chk, show;
    row = $(this);
    chk = function(kind){
      return check(row, filters[kind].filter(':checked').val());
    };
    show = row.hasClass('owned')
      ? chk('own')
      : row.hasClass('wished') && chk('wish') || chk('all');
    row.toggleClass('visibility-filter-hidden', !show);
  });
  for (kind in filters) {
    try {
      GM_setValue(kind, byVal(kind));
    } catch (e$) {}
  }
}
$('#visibility-filter input').change(updateFilters);
updateFilters();
setTimeout(updateFilters, 500);
setTimeout(updateFilters, 1500);
setTimeout(updateFilters, 3000);
$('h1').remove();
function applyStyle(css){
  $('<style>').html(css).appendTo('head');
}
