// ==UserScript==
// @name         SteamDB sales page improvements
// @description  Add buttons to hide non-"highest recorded discount"
// @version      3
// @include      https://steamdb.info/sales/*
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://blaxpirit.com/
// ==/UserScript==
// Generated by LiveScript 1.5.0
var $, ignoredStyle;
$ = jQuery;
$('.dataTables_length select').val(-1).trigger('change');
ignoredStyle = null;
$('<div class="steamy-checkbox-control" id="js-notinterested-checkbox"><div class="steamy-checkbox"></div><span class="steamy-checkbox-label">Hide "not interested"</span></div>').insertBefore('#js-merged-checkbox').click(function(){
  $(this).toggleClass('checked');
  if ($(this).hasClass('checked')) {
    ignoredStyle = $('<style>.ignored { display: none; }</style>').appendTo('head');
  } else {
    ignoredStyle.remove();
  }
}).click();
$('<div class="steamy-checkbox-control">\n    Show only lowest:\n    <span class="btn btn-sm btn-social">&le;</span>\n    <span class="btn btn-sm btn-social">&lt;</span>\n</div>').insertAfter('#js-merged-checkbox').find('span').click(function(){
  var sel;
  sel = $(this).text() === '<' ? ':not(:has(.price-discount-major))' : ':has(.highest-discount)';
  $("table.table-sales tr.app" + sel).hide();
});
