// ==UserScript==
// @name         SteamDB sales page improvements
// @description  Add buttons to hide non-"highest recorded discount"
// @version      6
// @include      https://steamdb.info/sales/*
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://blaxpirit.com/
// ==/UserScript==
// Generated by LiveScript 1.5.0
var $, appliedStyles, applyStyle, ref$, col1, col2;
$ = jQuery;
appliedStyles = {};
applyStyle = function(css, enable){
  enable == null && (enable = true);
  if (enable) {
    appliedStyles[css] = $('<style>').html(css).appendTo('head');
  } else {
    try {
      appliedStyles[css].remove();
    } catch (e$) {}
  }
};
$('.dataTables_length select').val(-1).change();
ref$ = $('#js-filters>div'), col1 = ref$[0], col2 = ref$[1];
$('<div class="steamy-checkbox-control"><div class="steamy-checkbox"></div><span class="steamy-checkbox-label">Hide "not interested"</span></div>').appendTo(col1).click(function(){
  var checked;
  checked = $(this).toggleClass('checked').hasClass('checked');
  applyStyle('.ignored { display: none; }', checked);
}).click();
$('<div class="fancy-select"><select><option value="all">Any discount</option><option value="le">Hide smaller discounts</option><option value="lt">Only new highest discounts</option></select></div>').prependTo(col1).find('select').change(function(){
  var val, kinds, selector, kind;
  val = $(this).val();
  kinds = {
    le: ':has(.highest-discount)',
    lt: ':not(:has(.price-discount-major))'
  };
  if (val !== 'all') {
    selector = 'table.table-sales tr.app' + kinds[val];
    $(selector).addClass("hide-" + val);
  }
  for (kind in kinds) {
    applyStyle(".hide-" + kind + " { display: none; }", val === kind);
  }
}).val('le').change();
$('#js-merged-checkbox').appendTo(col2);
$('.sales-weeklong-deals').removeClass('sales-weeklong-deals');
