// ==UserScript==
// @name         Steam prices round-up
// @description  Round up the prices on Steam $9.99 -> $10.00
// @version      2
// @include      http://store.steampowered.com/*
// @include      http://steamcommunity.com/*/wishlist
// @include      https://steamdb.info/*
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://blaxpirit.com/
// ==/UserScript==
// Generated by LiveScript 1.4.0
var run;
run = function(){
  var i$, ref$, len$, item;
  for (i$ = 0, len$ = (ref$ = document.querySelectorAll('.price:not(#cart_price_total), .discount_price, .discount_original_price,.discount_final_price, .table-sales td:nth-child(5)')).length; i$ < len$; ++i$) {
    item = ref$[i$];
    item.innerHTML = item.innerHTML.replace(/\b[0-9]+[.,][0-9][14689]\b/g, fn$);
  }
  function fn$(s){
    var n;
    n = parseFloat(s.replace(',', '.'));
    n = Math.round(n * 20) / 20;
    return n.toFixed(2);
  }
};
run();
setTimeout(run, 1500);
setInterval(run, 3000);
