// ==UserScript==
// @name         SteamDB Anti-Wilson
// @description  Replace Wilson ratings with simple percentages, like on Steam store
// @version      2
// @include      https://steamdb.info/sales/*
// @grant        none
// @run-at       document-end
// @author       Oleh Prypin
// @namespace    http://blaxpirit.com/
// ==/UserScript==
// Generated by LiveScript 1.5.0
var $, clamp, run;
$ = jQuery;
clamp = function(min, x, max){
  if (x < min) {
    return min;
  }
  if (x > max) {
    return max;
  }
  return x;
};
run = function(){
  $('.table-sales tbody span.tooltipped').each(function(){
    var el, tip, result, ref$, pos, neg, perc, total;
    el = $(this);
    tip = el.attr('aria-label');
    result = /([0-9]+).+?([0-9]+)/.exec(tip);
    ref$ = result.slice(1).map(function(it){
      return parseInt(it);
    }), pos = ref$[0], neg = ref$[1];
    perc = pos / (total = pos + neg);
    el.parent().parent().find('.b').each(function(){
      $(this).css({
        fontWeight: 100 + Math.round(Math.pow(perc, 2) * 8) * 100
      });
    });
    el.text(clamp(0, Math.round(perc * 100), 99) + "%").css({
      fontWeight: clamp(100, Math.ceil(Math.log(total) / Math.log(3)) * 100, 900)
    });
    el.parent().attr({
      dataSort: perc.toFixed(4)
    });
  });
};
run();
setTimeout(run, 500);
setTimeout(run, 1000);
setInterval(run, 2500);
